blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_home, name='blog_home'),
    path('<int:article_id>/', views.blog_article, name='blog_article'),
    path('blog-post/', views.blog_post, name='blog_post'),
]

course/urls.py
from django.urls import path
from .views import CourseHome, CourseListView, CourseCreateView, CourseDeleteView, CourseDetailView

app_name = 'course'

urlpatterns = [
    path('', CourseHome.as_view()),
    path('list/', CourseListView.as_view(), name='course_list'),
    path('create/', CourseCreateView.as_view(), name='course_create'),
    path('delete/<int:pk>/', CourseDeleteView.as_view(), name='course_delete'),  # pk为通用类定义的变量
    path('detail/<int:pk>/', CourseDetailView.as_view(), name='course_detail')
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.views import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('favicon.ico', serve, {'path': 'img/favicon.ico'}),  # 添加网站图标
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('blog.urls', namespace='root')),  # 网址主页为blog
    path('account/', include('account.urls', namespace='account')),
    path('course/', include('course.urls', namespace='course'))
]
# 为每个多媒体文件添加对应的urlpatterns的列表里元素
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/models.py
from django.db import models
from django.contrib.auth.models import User


def user_directory_path(instance, filename):
    return 'course/user_{0}/{1}'.format(instance.user.id, filename)


class Course(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='courses_user')
    title = models.CharField(max_length=200)
    overview = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    video = models.FileField(blank=True, upload_to='videos/')
    attach = models.FileField(blank=True, upload_to=user_directory_path)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

course/forms.py
from django import forms
from .models import Course


class CourseCreateForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ('title', 'overview', 'video', 'attach',)

course/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, DetailView
from .models import Course
from braces.views import LoginRequiredMixin
from django.views.generic.edit import CreateView, DeleteView
from .forms import CourseCreateForm
from django.urls import reverse_lazy
from django.http import HttpResponse
import json


class CourseHome(TemplateView):
    template_name = 'course/home.html'


class UserMixin:  # 筛选用户的类
    def get_queryset(self):
        qs = super(UserMixin, self).get_queryset()
        return qs.filter(user=self.request.user)


class UserCourseMixin(UserMixin, LoginRequiredMixin):  # 操作的模型
    model = Course  # 这里定义了model后面子类就不用再定义
    login_url = '/account/login/'


class CourseListView(UserCourseMixin, ListView):  # 多重继承
    # model = Course  # Course.objects.all()
    template_name = 'course/course_list.html'
    context_object_name = 'courses'  # 前端模板变量名


class CourseCreateView(UserCourseMixin, CreateView):
    fields = ['title', 'overview', 'video', 'attach']
    template_name = 'course/course_create.html'

    def post(self, request, *args, **kwargs):
        form = CourseCreateForm(request.POST, request.FILES)  # 接收Post数据与文件
        if form.is_valid():
            new_course = form.save(commit=False)
            new_course.user = self.request.user
            new_course.save()
            return redirect('course:course_list')
        return self.render_to_response({'form': form})


class CourseDeleteView(UserCourseMixin, DeleteView):
    success_url = reverse_lazy('course:course_list')

    def dispatch(self, *args, **kwargs):  # 重写方法，适应AJAX提交
        resp = DeleteView.dispatch(self, *args, **kwargs)
        if self.request.is_ajax():
            response_data = {'result': 'OK'}  # 是AJAX提交，用json返回OK
            return HttpResponse(json.dumps(response_data), content_type='application/json')
        else:
            return resp  # 非AJAX提交直接返回


class CourseDetailView(UserCourseMixin, DetailView):
    template_name = 'course/course_detail.html'

templates/course/course_create.html
{% extends 'base.html' %}

{% block title %}
    创建课程
{% endblock %}

{% block header %}
    {% include 'course_header.html' %}
{% endblock %}

{% block content %}
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <form action="." method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {# {{ form.as_p }} #}
                    <div class="row" style="margin-top: 10px;">
                        <div class="col-md-2">课程标题：</div>
                        <div class="col-md-10">{{ form.title }}</div>
                    </div>
                    <div class="row" style="margin-top: 10px;">
                        <div class="col-md-2">课程介绍：</div>
                        <div class="col-md-10">{{ form.overview }}</div>
                    </div>
                    <div class="row" style="margin-top: 10px;">
                        <div class="col-md-2">上传视频：</div>
                        <div class="col-md-10">{{ form.video }}</div>
                    </div>
                    <div class="row" style="margin-top: 10px;">
                        <div class="col-md-2">上传附件：</div>
                        <div class="col-md-10">{{ form.attach }}</div>
                    </div>
                    <input type="submit" value="发布课程">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/course/course_detail.html
{% extends 'base.html' %}

{% block title %}
    课程详情
{% endblock %}

{% block header %}
    {% include 'course_header.html' %}
{% endblock %}

{% block content %}
    <!-- Main Content -->
    <div class="container">
        <div class="row text-center">
            <div class="col-lg-8 col-md-10 mx-auto">
                <h1>{{ object.title }}</h1>
                <p>讲师：{{ object.user.username }}</p>
                <p>简介：{{ object.overview }}</p>
                {% if object.video %}
                    <video src="{{ object.video.url }}" controls="controls" width="800"></video>
                {% else %}
                    <p>没有视频内容</p>
                {% endif %}
                {% if object.attach %}
                    <p>下载课件：<a href="{{ object.attach.url }}">{{ object.attach.name | slice:"15:" }}</a></p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/course/course_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    课程列表
{% endblock %}

{% block header %}
    {% include 'course_header.html' %}
{% endblock %}

{% block content %}
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <table class="table table-hover">
                    <tr>
                        <td>序号</td>
                        <td>标题</td>
                        <td>讲师</td>
                        <td>日期</td>
                        <td>操作</td>
                    </tr>
                    {% for course in courses %}
                        <tr id="course_{{ course.id }}">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ course.title }}</td>
                            <td>{{ course.user.username }}</td>
                            <td>{{ course.created }}</td>
                            <td><a class="detail" target="_blank" href="{% url 'course:course_detail' course.id %}">
                                <i class="fa fa-search" aria-hidden="true"></i></a>
                                <a style="margin-left: 20px;" class="delete"
                                   href="{% url 'course:course_delete' course.id %}">
                                    <i class="fa fa-trash" aria-hidden="true"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
                <div class="text-right">
                    <a href="{% url 'course:course_create' %}">
                        <button type="button" class="btn btn-primary">发布课程</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var onDelete = function () {
                alert("Delete it?")

                $.ajaxSetup({
                    data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
                });

                $.post(this.href, function (data) {
                    if (data.result == "OK") {
                        window.location.reload()
                    } else {
                        alert("something is wrong.")
                    }
                }).fail(function () {
                    alert("error")
                })
                return false
            }

            $(".delete").click(onDelete)
        })
    </script>
{% endblock %}

templates/course/home.html
{% extends 'base.html' %}

{% block title %}
    网站课程
{% endblock %}

{% block header %}
    {% include 'backend_header.html' %}
{% endblock %}

{% block content %}
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <h1>Python全栈工程师课程</h1>
            </div>
        </div>
    </div>
{% endblock %}