blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_home, name='blog_home'),
    path('<int:article_id>/', views.blog_article, name='blog_article'),
    path('blog-post/', views.blog_post, name='blog_post'),
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.views import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('favicon.ico', serve, {'path': 'img/favicon.ico'}),  # 添加网站图标
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('blog.urls', namespace='root')),  # 网址主页为blog
    path('account/', include('account.urls', namespace='account')),
    path('course/', include('course.urls', namespace='course'))
]
# 为每个多媒体文件添加对应的urlpatterns的列表里元素
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class BlogArticles(models.Model):
    title = models.CharField(max_length=300)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_post')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)

    # 内部类
    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import BlogArticles


class BlogArticlesForm(forms.ModelForm):
    class Meta:
        model = BlogArticles
        fields = ('title', 'body',)

blog/views.py
from django.shortcuts import render
from .models import BlogArticles
from django.contrib.auth.decorators import login_required
from .forms import BlogArticlesForm
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def blog_home(request):
    blogs = BlogArticles.objects.all()
    paginator = Paginator(blogs, 3)
    page = request.GET.get('page')  # http://localhost:8000/blog/?page=1
    try:
        current_page = paginator.page(page)
    except PageNotAnInteger:
        current_page = paginator.page(1)
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
    current_blogs = current_page.object_list
    return render(request, 'blog/home.html', {'blogs': current_blogs, 'page': current_page})


def blog_article(request, article_id):
    article = BlogArticles.objects.get(id=article_id)
    pub = article.publish
    return render(request, 'blog/article.html', {'article': article, 'publish': pub})


@login_required
def blog_post(request):
    if request.method == 'GET':
        blog_form = BlogArticlesForm()
        return render(request, 'blog/post.html', {'blog_form': blog_form})
    if request.method == 'POST':
        blog_form = BlogArticlesForm(request.POST)
        if blog_form.is_valid():
            cd = blog_form.cleaned_data
            try:
                blog = blog_form.save(commit=False)
                blog.author = request.user
                blog.save()
                return HttpResponse('1')
            except:
                return HttpResponse('-1')
        else:
            return HttpResponse('0')

templates/blog/article.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    宁静致远 - {{ article.title }}
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}">
{% endblock %}

{% block header %}
    <!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static 'img/post-bg.jpg' %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="post-heading">
                        <h1 class="text-center">{{ article.title }}</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block content %}
    <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <p class="text-center">
                        <span>作者：{{ article.author.username }}</span>
                        <span style="margin-left: 10px">发布时间：{{ publish }}</span>
                    </p>
                    {# <div>{{ article.body }}</div> #}
                    <div id="editormd-view">
                        <textarea id="append-test" style="display: none;">
{{ article.body }}
                        </textarea>
                    </div>
                </div>
            </div>
        </div>
    </article>
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'editor/lib/marked.min.js' %}"></script>
    <script src="{% static 'editor/lib/prettify.min.js' %}"></script>
    <script src="{% static 'editor/lib/raphael.min.js' %}"></script>
    <script src="{% static 'editor/lib/underscore.min.js' %}"></script>
    <script src="{% static 'editor/lib/sequence-diagram.min.js' %}"></script>
    <script src="{% static 'editor/lib/flowchart.min.js' %}"></script>
    <script src="{% static 'editor/lib/jquery.flowchart.min.js' %}"></script>
    <script src="{% static 'editor/editormd.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            editormd.markdownToHTML("editormd-view", {
                htmlDecode: "style, script, iframe",
                emoji: true,
                taskList: true,
                tex: true,
                flowChart: true,
                sequenceDiagram: true,
            })
        })
    </script>
{% endblock %}

templates/blog/blog_post.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block header %}
    {% include 'backend_header.html' %}
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
{% endblock %}

{% block content %}
    <!-- Main Content -->
    <div class="container">
        <div class="row text-center">
            <div class="col-lg-9 col-md-11 mx-auto">
                <form class="form-horizontal" action="." method="post">
                    <div class="row">
                        <div class="">标题：</div>
                        <div class="">{{ blog_form.title }}</div>
                    </div>
                    <div class="row">
                        <div class="">内容：</div>
                        {# <div class="col-sm-10 text-left">{{ blog_form.body }}</div> #}
                        <div id="test-editor" class="">
                            <textarea style="display:none;" id="id_body"></textarea>
                        </div>
                    </div>
                    <input type="button" class="btn btn-primary" value="发布文章" onclick="post_blog()">
                </form>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
    <script type="text/javascript" src="{% static 'editor/editormd.min.js' %}"></script>
    <script type="text/javascript">
        function post_blog() {
            var title = $('#id_title').val()
            var body = $('#id_body').val()
            console.log(title, body)

            // django里ajax方式转递csrf的方式
            $.ajaxSetup({
                data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
            });

            $.ajax({
                url: "{% url 'blog:blog_post' %}",
                type: "POST",
                data: {'title': title, 'body': body},
                success: function (e) {
                    if (e == '1') {
                        layer.msg("文章发布成功！")
                        location.href = "{% url 'blog:blog_home' %}"
                    } else if (e == '-1') {
                        layer.msg("服务器繁忙。")
                    } else {
                        layer.msg("请检查输入的内容，不能为空。")
                    }
                }
            })
        }

        // 加载md编辑器的js代码
        $(function () {
            var editor = editormd("test-editor", {
                width: "100%",
                height: 640,
                syncScrolling: "single",
                path: "{% static 'editor/lib/' %}",
            })
        })
    </script>
{% endblock %}

templates/blog/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    博客文章
{% endblock %}

{% block header %}
    <!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static 'img/home-bg.jpg' %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>宁静致远</h1>
                        <span class="subheading">一个由Bootstrap和Django创建的博客</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block content %}
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                {% for blog in blogs %}
                    <div class="post-preview">
                        <a href="{{ blog.id }}"><h2 class="post-title">{{ blog.title }}</h2></a>
                        <p style="font: caption;" class="post-meta">作者：<a
                                href="#">{{ blog.author }}</a>　{{ blog.publish }}</p>
                    </div>
                    <hr>
                {% endfor %}
                <!-- Pager -->
                <div class="clearfix">
                    {% include 'paginator.html' %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/blog/post.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block header %}
    {% include 'backend_header.html' %}
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
{% endblock %}

{% block content %}
    <!-- Main Content -->
    <div class="container">
        <div class="row text-center">
            <div class="col-lg-9 col-md-11 mx-auto">
                <form class="form-horizontal" action="." method="post">
                    <div class="row">
                        <div class="">标题：</div>
                        <div class="">{{ blog_form.title }}</div>
                    </div>
                    <div class="row">
                        <div class="">内容：</div>
                        {# <div class="col-sm-10 text-left">{{ blog_form.body }}</div> #}
                        <div id="test-editor" class="">
                            <textarea style="display:none;" id="id_body"></textarea>
                        </div>
                    </div>
                    <input type="button" class="btn btn-primary" value="发布文章" onclick="post_blog()">
                </form>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
    <script type="text/javascript" src="{% static 'editor/editormd.min.js' %}"></script>
    <script type="text/javascript">
        function post_blog() {
            var title = $('#id_title').val()
            var body = $('#id_body').val()
            console.log(title, body)

            // django里ajax方式转递csrf的方式
            $.ajaxSetup({
                data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
            });

            $.ajax({
                url: "{% url 'blog:blog_post' %}",
                type: "POST",
                data: {'title': title, 'body': body},
                success: function (e) {
                    if (e == '1') {
                        layer.msg("文章发布成功！")
                        location.href = "{% url 'blog:blog_home' %}"
                    } else if (e == '-1') {
                        layer.msg("服务器繁忙。")
                    } else {
                        layer.msg("请检查输入的内容，不能为空。")
                    }
                }
            })
        }

        // 加载md编辑器的js代码
        $(function () {
            var editor = editormd("test-editor", {
                width: "100%",
                height: 640,
                syncScrolling: "single",
                path: "{% static 'editor/lib/' %}",
            })
        })
    </script>
{% endblock %}

templates/blog/titles.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}
    博客文章
{% endblock %}

{% block header %}
    <!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static 'img/home-bg.jpg' %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>宁静致远</h1>
                        <span class="subheading">一个由Bootstrap和Django创建的博客</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}



{% block content %}
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Man must explore, and this is exploration at its greatest
                        </h2>
                        <h3 class="post-subtitle">
                            Problems look mighty small from 150 miles up
                        </h3>
                    </a>
                    <p class="post-meta">Posted by
                        <a href="#">Start Bootstrap</a>
                        on September 24, 2019</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            I believe every human has a finite number of heartbeats. I don't intend to waste any of
                            mine.
                        </h2>
                    </a>
                    <p class="post-meta">Posted by
                        <a href="#">Start Bootstrap</a>
                        on September 18, 2019</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Science has not yet mastered prophecy
                        </h2>
                        <h3 class="post-subtitle">
                            We predict too much for the next year and yet far too little for the next ten.
                        </h3>
                    </a>
                    <p class="post-meta">Posted by
                        <a href="#">Start Bootstrap</a>
                        on August 24, 2019</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Failure is not an option
                        </h2>
                        <h3 class="post-subtitle">
                            Many say exploration is part of our destiny, but it’s actually our duty to future
                            generations.
                        </h3>
                    </a>
                    <p class="post-meta">Posted by
                        <a href="#">Start Bootstrap</a>
                        on July 8, 2019</p>
                </div>
                <hr>
                <!-- Pager -->
                <div class="clearfix">
                    <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}